### ISSUE TITLE
4. Build a CRUD through endpoints

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-start-a-little-project-#5]
# CRUD

## Task list

- [x] Get all users
- [x] Create new user
- [x] Get an user for given id
- [x] Update an user for given id
- [x] Delete an user for given id

## Documentation

[SQLAlchemy - Query the Data](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/quickstart/#query-the-data)

[SQLAlchemy - Modifying and Querying Data](https://flask-sqlalchemy.palletsprojects.com/en/3.0.x/queries/)
